### ISSUE TITLE
Paraview error on opening vtk file.

### ISSUE THREAD

**Issue by ghost** [tbetcke/PyPWDG#3]
When I run squarecommon.py and look at the generated vti/vtk files in paraview, I get the following message

"Application asked to unregister timer 0x30000019 which is not registered in this thread. Fix application."

Unsure what is causing it (PyPWDG or not)

**Comment by joelphillips** [comment]
you're on your own with that.

I find visit works fine.

**Comment by ghost** [comment]
Found source of error - bug in QT. No problem for us.

http://bugreports.qt.nokia.com/browse/QTBUG-16558
